### ISSUE TITLE
gradle?

### ISSUE THREAD

**Issue by Swisyn** [baoyongzhang/android-PullRefreshLayout#10]
Thank you for your amazing lib! I'd like to use it but it has to be downloaded as a module. Can you host it on gradle please?

**Comment by cdsap** [comment]
any news?

**Comment by Swisyn** [comment]
i've copy it and done with gradle > https://github.com/Swisyn/PullRefreshLayout

**Comment by cdsap** [comment]
@Swisyn thanks :+1:

**Comment by baoyongzhang** [comment]
I've added this
